### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ahmadajmi** [Health-Care/BloodDonation#9]
If I need to push to heroku or compile assets on local machine i get this issue

```
➜  BloodDonation git:(master) ✗ RAILS_ENV=production rake assets:clean assets:precompile

rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/sass_processor.rb:266:in `sprockets_context'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/sass_processor.rb:112:in `asset_path'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:140:in `_perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/node.rb:50:in `perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:170:in `perform_arg'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:124:in `block in _perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:124:in `each'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:124:in `each_with_index'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:124:in `each'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:124:in `map'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/funcall.rb:124:in `_perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/node.rb:50:in `perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/list_literal.rb:63:in `block in _perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/list_literal.rb:63:in `map'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/list_literal.rb:63:in `_perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/script/tree/node.rb:50:in `perform'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/stack.rb:79:in `block in with_base'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/stack.rb:115:in `with_frame'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/stack.rb:79:in `with_base'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:430:in `map'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/stack.rb:79:in `block in with_base'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/stack.rb:115:in `with_frame'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/stack.rb:79:in `with_base'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/tree/root_node.rb:20:in `render'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sass-3.4.16/lib/sass/engine.rb:278:in `render'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:48:in `call'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:28:in `call'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:45:in `block in load'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:38:in `load'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `yield'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:63:in `find_asset'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:70:in `find_all_linked_assets'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:130:in `block in find'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:129:in `each'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:129:in `find'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:162:in `compile'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-3.2.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ahmadajmi/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

I did some debugging and found that the issue happend with this file `app/assets/admin.css` line
```
//= require_tree ../admin_css
```

**Comment by ahmadajmi** [comment]
#10

**Comment by ibrahimali123** [comment]
in file assets/stylesheets/admin.css  in this file i call //= require_tree ../admin_css
and assets/admin_css is a folder containing all css of admin layout.

in /stylesheets you can delete all files except admin and 2 files starting with my name.

regardless asssts/javascripts/ i need all files in it.

**Comment by ibrahimali123** [comment]
to solve the error make sure that you have all the files on master (clone it).

if you get errors again delete assets/admin_js and assets/admin_css folders
and assets/stylesheets/admin.css and assets/javascripts/admin.js files

and delete those 2 lines:
Rails.application.config.assets.precompile += %w( admin.css )
Rails.application.config.assets.precompile += %w( admin.js )
in BloodDonation\config\application.rb

**Comment by ahmadajmi** [comment]
@ibrahimali123 
Ok great, can you please make a pull request with these suggestions

**Comment by ahmadajmi** [comment]
@ibrahimali123 
This is the last PR https://github.com/Health-Care/BloodDonation/pull/10 and it's merged to the master, so pls pull first

**Comment by ibrahimali123** [comment]
@ahmadajmi  7ader, I will see this issue.

**Comment by ahmadajmi** [comment]
@ibrahimali123 any updateds

**Comment by ibrahimali966** [comment]
@ahmadajmi Yes check the updates
